// File: uart_tx_datapath.v
// Author: Diego Dominguez
// Hierarchy: UART transmitter datapath
// Version history:
//  v1.0  2026-09-26  Initial UART transmitter datapath design,
//                   including documentation and naming convention
//
// Description:
// This module implements the operational path of the UART transmitter.
// It selects the bit to send from the input byte, updates the bit
// counter, and drives the serial output signal according to control
// signals generated by the FSM.
//
// Functional blocks:
//  - uart_tx_register: serializes the selected bit to the tx line
//  - uart_baud_tick_gen: emits the baud-rate tick signal
//  - uart_bit_counter: tracks the current transmitted bit position
module uart_tx_datapath(
    input clk,
    input [7:0] data_in,
    input bit_select_en,
    input bit_counter_en,
    input idle_high_en,
    output byte_done,
    output baud_tick,
    output reg tx_serial
);

  wire next_tx_bit;
  reg [2:0] bit_index;

  // Data selection logic. When the control path enables a transmission
  // cycle, the current bit is chosen from the input byte. Otherwise, the
  // default idle value is driven.
  assign next_tx_bit = (bit_select_en & data_in[bit_index]) |
                       (idle_high_en & 1'b1);

  // Serial register: loads the selected bit at each clock edge.
  uart_tx_register tx_register_inst(
    .clk(clk),
    .d(next_tx_bit),
    .q(tx_serial)
  );

  // Baud generator: produces the timing tick used to serialize each bit.
  uart_baud_tick_gen baud_tick_gen_inst(
    .clk(clk),
    .tick(baud_tick)
  );

  // Byte counter: advances the bit index. When the byte is complete, it
  // asserts byte_done to inform the control FSM that the transmission has
  // ended.
  uart_bit_counter bit_counter_inst(
    .clk(clk),
    .bit_index(bit_index),
    .tick(byte_done),
    .en(bit_counter_en)
  );

endmodule

